---
variables:
  TF_MIN_VERSION: "0.13"
  AZURERM_PROVIDER_MIN_VERSION: "2.7"

include:
  - template: 'Workflows/Branch-Pipelines.gitlab-ci.yml'
  - project: 'claranet/projects/cloud/azure/terraform/ci'
    ref: AZ-572-add-configuration-file
    file: '/pipeline.yml'
...
